kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      auto_tag: true
      repo: zlyuan/drone-build-notify
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
